### ISSUE TITLE
Loaded question: output to emulators, webassembly + canvas?

### ISSUE THREAD

**Issue by sprive** [Fabrizio-Caruso/CROSS-LIB#291] opened 2023-07-18 17:26 UTC
Hello,

Awesome project. Would it ever be possible to extend the supported platform/targets, to include the browser (webassembly + canvas)? 

There exist some emulators that compile well into webassembly..  emulators for hardware you already support (c64 etc). "IF"  CROSS-LIB could include these emulators (and you build them using web-assembly), "and" you define in the webpage that it should auto-load that project you just built using CROSS-LIB... then you might be able to target the web.

Quite a few "ifs" and "ands" on my part, but just asking. Cheers

**Comment by Fabrizio-Caruso** [comment] 2023-07-19 09:38
@sprive you are talking about two very different things.
Concerning a Webassembly/Javascript target, the answer is a "very partial yes".
I could run some experiments with emscripten. In theory I can build very ugly turn-based only versions of my game with horrible input.
So the problem is that I would have to learn how to implement the input. I am not fluent in Javascript. Can you help?

Concerning the emulators, you can alreay run and play some of my games (I will add the last 2 asap) on the browser.
Some of the Javascript emulators I use (Vic20, C64, VZ200, Laser 500) auto-load whatever binary I release (or re-upload in the GitHub release).

You can play the games online here:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/docs/GAMES.md

For some debugging I don't even need an emulator or a browser as I can build my games for the PC terminal.
I don't even need any cross-compiler.

Example:
`xl bomber` -> builds the game "Bomber" for whatever terminal it is used to run the "xl" script (this requires a native compiler such as gcc and ncurses)

**Comment by sprive** [comment] 2023-07-20 19:54
Hi @Fabrizio-Caruso 

Yes, sorry 2 things :-) 

> Concerning the emulators, you can already run and play some of my games (I will add the last 2 asap) on the browser.
> You can play some of the games online here:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/docs/GAMES.md

YES exactly this. :-) 
I guess manually adding the links manually isn't so bad given that only some use cases work well for it and text is still a problem.
...

I have dabbled with Emscripten, and (not the library's fault fault) I've been both amazed that it works, and also frustrated with any getting browser based text input working with it. Pyscript seems very interesting but have not tried yet.

Yes, I can help, but for this type of project my skills (Python, networking, and requests) they would be limited to testing, and a little bit of C coding. No JS, presently.   Let me know if there's an issue that fits, else I will continue following this until someone fluent in JS can help.

**Comment by Fabrizio-Caruso** [comment] 2023-07-20 20:04
@sprive Hi again,

Consider also that the WebAssembly/JS as a target is also out of scope for Cross-Lib, whose goal is to provide a hardware abstraction layer for vintage systems (mostly 8-bits) and some helping scripts (to build, manage project, handle abstract assets, etc.).
Nevertheless, if I manage to figure out how to get some "immediate input" working, I would be more than happy to support it as a target.

I am closing this "issue", but feel free to post related questions here.

**Closed by Fabrizio-Caruso** 2023-07-20 20:04 UTC

**Comment by Fabrizio-Caruso** [comment] 2023-07-21 22:47
@sprive just to let you know that I am actively improving the xl script (with fixes, minor additions in the commands and some cosmetic improvements such as colored text to highlight warnings, errors, succeeded tests, makefile commands, etc. ).
So I invite you to pull the latest changes. Would you let me know if it has improved for you?

**Comment by sprive** [comment] 2023-07-26 00:20
@Fabrizio-Caruso Thanks. 
1. On the WASM stuff, I'm starting to look at fantasy console https://wasm4.org/
I get WASM-4 and CROSS-LIB are different purposes. 
My primary use case is running in a browser, but if the same code runs on a retro platform that is a big plus.
(WASM-4 will never target retro hardware so that's a limiter there).
 Thanks for taking this odd request seriously. 

2. Yes, I'll be a back with feedback (I will take time, don't have a retro dev env or this library setup).   I've followed the AtariAge and YouTube posts on your project, but I haven't actually used CROSS-LIB yet :-)

**Comment by sprive** [comment] 2023-07-26 00:27
@Fabrizio-Caruso And earlier, when I asked about WASM, I phrased that wrong.
What I really meant was "target the browser" (with workflow conveniences).

The distinction being that including/bundling a page which invokes a bundled (someone else's) JS-based emulator and the project you just built, achieves all that that without CROSS LIB ever knowing anything about WASM. 

The build scripts look pretty neat. Just starting to RTFM here. Thanks
