### ISSUE TITLE
ld65: Warning: cross_lib/cfg//cc65/vic20-8k_GFX.cfg(17): Segment 'CODE' overflows memory area 'RAMEXP' by 3 bytes

### ISSUE THREAD

**Issue by 6809-user** [Fabrizio-Caruso/CROSS-LIB#278] opened 2022-03-03 11:43 UTC
vic20 target not building.
last 4 lines of ./xl chase vic20:
-o ../build/Xchase_vic20_exp_8k.prg
ld65: Warning: cross_lib/cfg//cc65/vic20-8k_GFX.cfg(17): Segment 'CODE' overflows memory area 'RAMEXP' by 3 bytes
ld65: Error: Cannot generate most of the files due to memory area overflow 
make: *** [games/chase/makefiles.chase/Makefile.cc65_targets:1091: vic20_exp_8k] Error 1

**Comment by Fabrizio-Caruso** [comment] 2022-03-03 17:54
@6809-user Thanks! This is probably not a bug. Are you using the very latest CC65 version? or the one provided in Ubuntu? I can try to save 3 bytes somehow... 
I can build Cross Chase for the Vic 20 (exp 8k is the default for Cross Chase).

**Comment by Fabrizio-Caruso** [comment] 2022-03-03 17:55
Meanwhile you can build the other Vic 20 versions with:
```
xl chase vic20_exp_16k
xl chase vic20_exp_3
xl chase vic20_unexpanded
```

**Comment by Fabrizio-Caruso** [comment] 2022-03-03 19:42
I can also make vic20_exp_16k the default version for vic20. This would make it build even with less optimized older version of CC65.

Could you please confirm what I suspect? i.e., that you are using whatever Ubuntu has in its repository and not the latest version of CC65 (e.g., for example by building it from source).

**Comment by Fabrizio-Caruso** [comment] 2022-03-03 19:49
I have just made the vic20_exp_16k the default for vic20. This should work also with an older less optimized CC65.
I am closing this issue but feel free to reply here.

**Closed by Fabrizio-Caruso** 2022-03-03 19:49 UTC

**Comment by 6809-user** [comment] 2022-03-04 08:34
Did not know some of the machines had submodels.
I tried to update cc65 from git, but got an error from checkinstall saying: Makefile:108: *** variable "PREFIX" must be set.  Stop.
make: *** [Makefile:6: install] Error 2

So used sudo PREFIX=/usr/local checkinstall
It built and installed the package but got a whole bunch of errors in:
 ========================= Installation results ===========================
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
BUILD_ID: Git d36800591
install -d /usr/local/bin
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
install ../bin/* /usr/local/bin
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/local/lib/checkinstall/installwatch.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
install -d /usr/local/share/cc65/lib

and so on...
At least the missing 3-byte error is gone :)
Meanwhile cannot figure out why (vice) xvic will not smart attach the examples, it just sits there without loading/running said example.
x64 works fine on the c64 examples...

**Comment by Fabrizio-Caruso** [comment] 2022-03-04 09:21
I support many sub-targets for many systems including exotic configs, e.g., C128 Z80 CPU in mode 128 40 and 80 columns.

You need to follow the installation guide for CC65. I have managed to build it under Lubuntu not too long ago. I don't remember the details. If it is a bug, I would advice that you open an issue in CC65 GitHub page. I saw there has been an issue on some 64 bit configs but I don't think it is your exact case.
